name: Train-in-the-cloud
 
on: [push]
 
jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: deploy
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --single \
          --cloud aws \
          --cloud-region us-west \
          --cloud-type=t2.medium \
          --labels=cml-runner
 
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: 
      image: docker://iterativeai/cml:0-dvc2-base1
      options: --shm-size=4g
 
    steps:
    - uses: actions/checkout@v2
 
    - name: "Train my model"
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        python --version
        pip install -r requirements.txt
        python train.py
 
        echo "## Report from your EC2 Instance" > report.md
        cat metrics.txt >> report.md
        cml-publish "training_history.png" --md >> report.md
        cml-send-comment report.md
